import type { ChapterMeta } from "../types"

/**
 * 13 章的学习路径。
 *
 * 顺序是**重排过**的，不是照抄原图。原图把「16种时态」放在最前面当门面，
 * 但那是最需要前置知识的部分（要先知道动词怎么活用才谈得上时和体），
 * 所以这里挪到 L3，前面先铺发音、词性、句型。
 */
export const CHAPTER_META: ChapterMeta[] = [
  {
    id: "ch01",
    no: 1,
    title: "五十音与四类发音",
    titleJa: "五十音・清音・濁音・半濁音・拗音",
    level: 1,
    summaryZh: "先把音读准：五十音表怎么排的，浊音半浊音拗音各是什么规律。",
    prerequisites: [],
    sourceSection: "一、基础知识",
  },
  {
    id: "ch02",
    no: 2,
    title: "10 种词性：一句话认出每一类",
    titleJa: "品詞の見分け方",
    level: 1,
    summaryZh: "看词尾就能判断词性，只有几个例外要单独记。",
    prerequisites: ["ch01"],
    sourceSection: "二、10种单词词性",
  },
  {
    id: "ch03",
    no: 3,
    title: "人称・指示・物主・反身代词",
    titleJa: "人称代名詞・こそあど",
    level: 1,
    summaryZh: "我你他怎么说，「我的」怎么说，これ／それ／あれ／どれ 怎么分。",
    prerequisites: ["ch02"],
    sourceSection: "三、日语人称代词 + 反身代词（原图此处有错，见勘误）",
  },
  {
    id: "ch04",
    no: 4,
    title: "8 种句子结构",
    titleJa: "文の骨組み",
    level: 2,
    summaryZh: "日语句子谓语永远在最后，助词决定谁是主语谁是宾语。",
    prerequisites: ["ch02", "ch03"],
    sourceSection: "五、8个句子结构",
  },
  {
    id: "ch05",
    no: 5,
    title: "4 种句子种类与 4 类疑问句",
    titleJa: "平叙・疑問・命令・感嘆",
    level: 2,
    summaryZh: "陈述、疑问、祈使、感叹，各自靠句尾的什么信号区分。",
    prerequisites: ["ch04"],
    sourceSection: "六、4种句子种类",
  },
  {
    id: "ch06",
    no: 6,
    title: "20 个疑问词",
    titleJa: "疑問詞 20",
    level: 2,
    summaryZh: "问什么、问哪里、问为什么——一张表配齐提问场景。",
    prerequisites: ["ch05"],
    sourceSection: "四、20个日语疑问词",
  },
  {
    id: "ch07",
    no: 7,
    title: "时与体：日语只有过去和非过去",
    titleJa: "テンスとアスペクト",
    level: 3,
    summaryZh: "日语没有16种时态。只有「过去／非过去」两档，剩下的靠 ている 表示状态。",
    prerequisites: ["ch04"],
    sourceSection: "日语16种时态（原图框架有误，本章重构）",
  },
  {
    id: "ch08",
    no: 8,
    title: "8 组时间标志词",
    titleJa: "時を表す言葉",
    level: 3,
    summaryZh: "毎日／昨日／明日……看到这些词就知道句子该用哪一档时态。",
    prerequisites: ["ch07"],
    sourceSection: "八大时态标志词",
  },
  {
    id: "ch09",
    no: 9,
    title: "动词三类分法与 8 个基础活用形",
    titleJa: "動詞の分類と活用形",
    level: 3,
    summaryZh: "先分清一类二类三类，剩下的活用全是按类套公式。",
    prerequisites: ["ch07"],
    sourceSection: "十、动词基础活用形",
  },
  {
    id: "ch10",
    no: 10,
    title: "进阶态：可能・使役・被动・使役被动・自发",
    titleJa: "可能・使役・受身・使役受身・自発",
    level: 4,
    summaryZh: "五种态各自改变「谁在做、谁受影响」，形近但意思差很远。",
    prerequisites: ["ch09"],
    sourceSection: "十、动词完整活用变形",
  },
  {
    id: "ch11",
    no: 11,
    title: "意志形与命令形",
    titleJa: "意志形・命令形",
    level: 4,
    summaryZh: "同一件事，说成提议还是命令，只差一个词尾——但语气差到能得罪人。",
    prerequisites: ["ch09"],
    sourceSection: "十、意志形 / 命令形",
  },
  {
    id: "ch12",
    no: 12,
    title: "条件句四大分支 ば／と／たら／なら",
    titleJa: "条件表現の四分岐",
    level: 5,
    summaryZh: "四个都翻译成「如果」，但能不能互换取决于前后件的时间关系。",
    prerequisites: ["ch09", "ch07"],
    sourceSection: "十一、条件句式四大分支",
  },
  {
    id: "ch13",
    no: 13,
    title: "特殊句式：存在・强调・倒装・宾补・同格",
    titleJa: "存在文・強調構文・倒置",
    level: 5,
    summaryZh: "ある／いる 怎么选，「のは〜だ」怎么把重点顶到前面。",
    prerequisites: ["ch04"],
    sourceSection: "七、4种特殊句式 + 宾语补足语 / 同格语",
  },
]

export const CHAPTER_META_BY_ID = new Map(CHAPTER_META.map((c) => [c.id, c]))
