import type { VerbEntry } from "./types"

export const VERB_CORPUS: VerbEntry[] = [
  // ======== 書く ========
  {
    id: "kaku",
    dictionaryForm: "書く",
    verbGroup: "godan",
    meaningZh: "写",
    conjugations: [
      {
        conjugationType: "passive",
        conjugatedForm: "書かれる",
        explanationZh: "被写；也可表示受到动作影响（迷惑受身）",
        patternHint: "五段：語幹 + あ段 + れる（書く → 書か + れる）",
        examples: [
          {
            japanese: "報告書は部長に書かれました。",
            tokens: [
              { text: "報告書", kana: "ほうこくしょ" },
              { text: "は" },
              { text: "部長", kana: "ぶちょう" },
              { text: "に" },
              { text: "書", kana: "か" },
              { text: "かれました。" },
            ],
            kana: "ほうこくしょはぶちょうにかかれました。",
            chinese: "报告由部长撰写了。",
            scene: "work",
            register: "丁寧",
          },
          {
            japanese: "壁に落書きを書かれてしまった。",
            tokens: [
              { text: "壁", kana: "かべ" },
              { text: "に" },
              { text: "落書", kana: "らくが" },
              { text: "きを" },
              { text: "書", kana: "か" },
              { text: "かれてしまった。" },
            ],
            kana: "かべにらくがきをかかれてしまった。",
            chinese: "墙上被人涂了鸦。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
      {
        conjugationType: "causative",
        conjugatedForm: "書かせる",
        explanationZh: "让…写；命令或允许某人写",
        patternHint: "五段：語幹 + あ段 + せる（書く → 書か + せる）",
        examples: [
          {
            japanese: "部下に議事録を書かせた。",
            tokens: [
              { text: "部下", kana: "ぶか" },
              { text: "に" },
              { text: "議事録", kana: "ぎじろく" },
              { text: "を" },
              { text: "書", kana: "か" },
              { text: "かせた。" },
            ],
            kana: "ぶかにぎじろくをかかせた。",
            chinese: "让下属写了会议记录。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "子供に感謝の手紙を書かせた。",
            tokens: [
              { text: "子供", kana: "こども" },
              { text: "に" },
              { text: "感謝", kana: "かんしゃ" },
              { text: "の" },
              { text: "手紙", kana: "てがみ" },
              { text: "を" },
              { text: "書", kana: "か" },
              { text: "かせた。" },
            ],
            kana: "こどもにかんしゃのてがみをかかせた。",
            chinese: "让孩子写了一封感谢信。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
      {
        conjugationType: "causativePassive",
        conjugatedForm: "書かせられる",
        explanationZh: "被迫写；被强制要求去写",
        patternHint: "五段：書か + せられる（口語では書かされる も可）",
        examples: [
          {
            japanese: "毎回、長い報告書を書かせられる。",
            tokens: [
              { text: "毎回", kana: "まいかい" },
              { text: "、" },
              { text: "長", kana: "なが" },
              { text: "い" },
              { text: "報告書", kana: "ほうこくしょ" },
              { text: "を" },
              { text: "書", kana: "か" },
              { text: "かせられる。" },
            ],
            kana: "まいかい、ながいほうこくしょをかかせられる。",
            chinese: "每次都被迫写很长的报告。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "小学生のとき、日記を毎日書かせられた。",
            tokens: [
              { text: "小学生", kana: "しょうがくせい" },
              { text: "のとき、" },
              { text: "日記", kana: "にっき" },
              { text: "を" },
              { text: "毎日", kana: "まいにち" },
              { text: "書", kana: "か" },
              { text: "かせられた。" },
            ],
            kana: "しょうがくせいのとき、にっきをまいにちかかせられた。",
            chinese: "上小学时每天都被强迫写日记。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
    ],
  },

  // ======== 読む ========
  {
    id: "yomu",
    dictionaryForm: "読む",
    verbGroup: "godan",
    meaningZh: "读",
    conjugations: [
      {
        conjugationType: "passive",
        conjugatedForm: "読まれる",
        explanationZh: "被读；内容被他人阅读",
        patternHint: "五段：語幹 + あ段 + れる（読む → 読ま + れる）",
        examples: [
          {
            japanese: "企画書が役員全員に読まれた。",
            tokens: [
              { text: "企画書", kana: "きかくしょ" },
              { text: "が" },
              { text: "役員", kana: "やくいん" },
              { text: "全員", kana: "ぜんいん" },
              { text: "に" },
              { text: "読", kana: "よ" },
              { text: "まれた。" },
            ],
            kana: "きかくしょがやくいんぜんいんによまれた。",
            chinese: "企划书被所有高管阅读了。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "日記を弟に読まれてしまった。",
            tokens: [
              { text: "日記", kana: "にっき" },
              { text: "を" },
              { text: "弟", kana: "おとうと" },
              { text: "に" },
              { text: "読", kana: "よ" },
              { text: "まれてしまった。" },
            ],
            kana: "にっきをおとうとによまれてしまった。",
            chinese: "日记被弟弟偷看了。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
      {
        conjugationType: "causative",
        conjugatedForm: "読ませる",
        explanationZh: "让…读；要求某人阅读",
        patternHint: "五段：語幹 + あ段 + せる（読む → 読ま + せる）",
        examples: [
          {
            japanese: "新人に規則を読ませてください。",
            tokens: [
              { text: "新人", kana: "しんじん" },
              { text: "に" },
              { text: "規則", kana: "きそく" },
              { text: "を" },
              { text: "読", kana: "よ" },
              { text: "ませてください。" },
            ],
            kana: "しんじんにきそくをよませてください。",
            chinese: "请让新员工读一下规定。",
            scene: "work",
            register: "丁寧",
          },
          {
            japanese: "子供に毎晩絵本を読ませる。",
            tokens: [
              { text: "子供", kana: "こども" },
              { text: "に" },
              { text: "毎晩", kana: "まいばん" },
              { text: "絵本", kana: "えほん" },
              { text: "を" },
              { text: "読", kana: "よ" },
              { text: "ませる。" },
            ],
            kana: "こどもにまいばんえほんをよませる。",
            chinese: "每晚让孩子读绘本。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
      {
        conjugationType: "causativePassive",
        conjugatedForm: "読まされる",
        explanationZh: "被迫读；被强制要求阅读（五段缩约形）",
        patternHint: "五段縮約：読ま + される（読ませられる の口語形）",
        examples: [
          {
            japanese: "会議前に大量の資料を読まされた。",
            tokens: [
              { text: "会議", kana: "かいぎ" },
              { text: "前", kana: "まえ" },
              { text: "に" },
              { text: "大量", kana: "たいりょう" },
              { text: "の" },
              { text: "資料", kana: "しりょう" },
              { text: "を" },
              { text: "読", kana: "よ" },
              { text: "まされた。" },
            ],
            kana: "かいぎまえにたいりょうのしりょうをよまされた。",
            chinese: "开会前被要求阅读了大量资料。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "学校で難しい本を読まされた。",
            tokens: [
              { text: "学校", kana: "がっこう" },
              { text: "で" },
              { text: "難", kana: "むずか" },
              { text: "しい" },
              { text: "本", kana: "ほん" },
              { text: "を" },
              { text: "読", kana: "よ" },
              { text: "まされた。" },
            ],
            kana: "がっこうでむずかしいほんをよまされた。",
            chinese: "在学校被强迫读了很难的书。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
    ],
  },

  // ======== 話す ========
  {
    id: "hanasu",
    dictionaryForm: "話す",
    verbGroup: "godan",
    meaningZh: "说；讲",
    conjugations: [
      {
        conjugationType: "passive",
        conjugatedForm: "話される",
        explanationZh: "被谈论；自己的事被他人说出去",
        patternHint: "五段：語幹 + あ段 + れる（話す → 話さ + れる）",
        examples: [
          {
            japanese: "会議で自分のミスを話されて困った。",
            tokens: [
              { text: "会議", kana: "かいぎ" },
              { text: "で" },
              { text: "自分", kana: "じぶん" },
              { text: "のミスを" },
              { text: "話", kana: "はな" },
              { text: "されて" },
              { text: "困", kana: "こま" },
              { text: "った。" },
            ],
            kana: "かいぎでじぶんのみすをはなされてこまった。",
            chinese: "在会议上被人说出了自己的失误，很难堪。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "秘密を友達に話されてしまった。",
            tokens: [
              { text: "秘密", kana: "ひみつ" },
              { text: "を" },
              { text: "友達", kana: "ともだち" },
              { text: "に" },
              { text: "話", kana: "はな" },
              { text: "されてしまった。" },
            ],
            kana: "ひみつをともだちにはなされてしまった。",
            chinese: "秘密被朋友说出去了。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
      {
        conjugationType: "causative",
        conjugatedForm: "話させる",
        explanationZh: "让…说；让某人发言或讲述",
        patternHint: "五段：語幹 + あ段 + せる（話す → 話さ + せる）",
        examples: [
          {
            japanese: "部長は新人に自己紹介を話させた。",
            tokens: [
              { text: "部長", kana: "ぶちょう" },
              { text: "は" },
              { text: "新人", kana: "しんじん" },
              { text: "に" },
              { text: "自己紹介", kana: "じこしょうかい" },
              { text: "を" },
              { text: "話", kana: "はな" },
              { text: "させた。" },
            ],
            kana: "ぶちょうはしんじんにじこしょうかいをはなさせた。",
            chinese: "部长让新员工做了自我介绍。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "先生が生徒に体験談を話させた。",
            tokens: [
              { text: "先生", kana: "せんせい" },
              { text: "が" },
              { text: "生徒", kana: "せいと" },
              { text: "に" },
              { text: "体験談", kana: "たいけんだん" },
              { text: "を" },
              { text: "話", kana: "はな" },
              { text: "させた。" },
            ],
            kana: "せんせいがせいとにたいけんだんをはなさせた。",
            chinese: "老师让学生分享了各自的亲身经历。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
      {
        conjugationType: "causativePassive",
        conjugatedForm: "話させられる",
        explanationZh: "被迫发言；被强制要求开口说",
        patternHint: "五段：話さ + せられる",
        examples: [
          {
            japanese: "急に全員の前で話させられた。",
            tokens: [
              { text: "急", kana: "きゅう" },
              { text: "に" },
              { text: "全員", kana: "ぜんいん" },
              { text: "の" },
              { text: "前", kana: "まえ" },
              { text: "で" },
              { text: "話", kana: "はな" },
              { text: "させられた。" },
            ],
            kana: "きゅうにぜんいんのまえではなさせられた。",
            chinese: "突然被要求在所有人面前发言了。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "パーティーで無理やりスピーチを話させられた。",
            tokens: [
              { text: "パーティーで" },
              { text: "無理", kana: "むり" },
              { text: "やりスピーチを" },
              { text: "話", kana: "はな" },
              { text: "させられた。" },
            ],
            kana: "ぱーてぃーでむりやりすぴーちをはなさせられた。",
            chinese: "在派对上被硬拉着做了演讲。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
    ],
  },

  // ======== 待つ ========
  {
    id: "matsu",
    dictionaryForm: "待つ",
    verbGroup: "godan",
    meaningZh: "等",
    conjugations: [
      {
        conjugationType: "passive",
        conjugatedForm: "待たれる",
        explanationZh: "被等；让对方等候（常含抱歉意味）",
        patternHint: "五段：語幹 + あ段 + れる（待つ → 待た + れる）",
        examples: [
          {
            japanese: "お客様に長い時間待たれてしまいました。",
            tokens: [
              { text: "お" },
              { text: "客様", kana: "きゃくさま" },
              { text: "に" },
              { text: "長", kana: "なが" },
              { text: "い" },
              { text: "時間", kana: "じかん" },
              { text: "待", kana: "ま" },
              { text: "たれてしまいました。" },
            ],
            kana: "おきゃくさまにながいじかんまたれてしまいました。",
            chinese: "让客户等了很长时间，真是抱歉。",
            scene: "work",
            register: "丁寧",
          },
          {
            japanese: "彼女に駅で一時間待たれた。",
            tokens: [
              { text: "彼女", kana: "かのじょ" },
              { text: "に" },
              { text: "駅", kana: "えき" },
              { text: "で" },
              { text: "一時間", kana: "いちじかん" },
              { text: "待", kana: "ま" },
              { text: "たれた。" },
            ],
            kana: "かのじょにえきでいちじかんまたれた。",
            chinese: "被女友在车站等了整整一个小时。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
      {
        conjugationType: "causative",
        conjugatedForm: "待たせる",
        explanationZh: "让…等；使某人等候",
        patternHint: "五段：語幹 + あ段 + せる（待つ → 待た + せる）",
        examples: [
          {
            japanese: "お客様をこれ以上待たせるわけにはいきません。",
            tokens: [
              { text: "お" },
              { text: "客様", kana: "きゃくさま" },
              { text: "をこれ" },
              { text: "以上", kana: "いじょう" },
              { text: "待", kana: "ま" },
              { text: "たせるわけにはいきません。" },
            ],
            kana: "おきゃくさまをこれいじょうまたせるわけにはいきません。",
            chinese: "不能再让客户继续等下去了。",
            scene: "work",
            register: "丁寧",
          },
          {
            japanese: "友達をカフェで待たせてしまった。",
            tokens: [
              { text: "友達", kana: "ともだち" },
              { text: "をカフェで" },
              { text: "待", kana: "ま" },
              { text: "たせてしまった。" },
            ],
            kana: "ともだちをかふぇでまたせてしまった。",
            chinese: "让朋友在咖啡馆一直等着了。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
      {
        conjugationType: "causativePassive",
        conjugatedForm: "待たされる",
        explanationZh: "被迫等候；被晾在一边（五段缩约形）",
        patternHint: "五段縮約：待た + される（待たせられる の口語形）",
        examples: [
          {
            japanese: "受付で三十分も待たされた。",
            tokens: [
              { text: "受付", kana: "うけつけ" },
              { text: "で" },
              { text: "三十分", kana: "さんじゅっぷん" },
              { text: "も" },
              { text: "待", kana: "ま" },
              { text: "たされた。" },
            ],
            kana: "うけつけでさんじゅっぷんもまたされた。",
            chinese: "在前台被晾了整整三十分钟。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "病院でいつも長い時間待たされる。",
            tokens: [
              { text: "病院", kana: "びょういん" },
              { text: "でいつも" },
              { text: "長", kana: "なが" },
              { text: "い" },
              { text: "時間", kana: "じかん" },
              { text: "待", kana: "ま" },
              { text: "たされる。" },
            ],
            kana: "びょういんでいつもながいじかんまたされる。",
            chinese: "在医院总是被要求等很长时间。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
    ],
  },

  // ======== 使う ========
  {
    id: "tsukau",
    dictionaryForm: "使う",
    verbGroup: "godan",
    meaningZh: "用；使用",
    conjugations: [
      {
        conjugationType: "passive",
        conjugatedForm: "使われる",
        explanationZh: "被使用；被人使唤",
        patternHint: "五段：語幹 + あ段 + れる（使う → 使わ + れる）",
        examples: [
          {
            japanese: "このシステムは全社員に使われています。",
            tokens: [
              { text: "このシステムは" },
              { text: "全社員", kana: "ぜんしゃいん" },
              { text: "に" },
              { text: "使", kana: "つか" },
              { text: "われています。" },
            ],
            kana: "このしすてむはぜんしゃいんにつかわれています。",
            chinese: "这套系统正在被全体员工使用。",
            scene: "work",
            register: "丁寧",
          },
          {
            japanese: "このバッグはもう使われていない。",
            tokens: [
              { text: "このバッグはもう" },
              { text: "使", kana: "つか" },
              { text: "われていない。" },
            ],
            kana: "このばっぐはもうつかわれていない。",
            chinese: "这个包已经没人用了。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
      {
        conjugationType: "causative",
        conjugatedForm: "使わせる",
        explanationZh: "让…使用；允许或命令使用",
        patternHint: "五段：語幹 + あ段 + せる（使う → 使わ + せる）",
        examples: [
          {
            japanese: "会議室を使わせていただけますか。",
            tokens: [
              { text: "会議室", kana: "かいぎしつ" },
              { text: "を" },
              { text: "使", kana: "つか" },
              { text: "わせていただけますか。" },
            ],
            kana: "かいぎしつをつかわせていただけますか。",
            chinese: "请问可以让我们使用会议室吗？",
            scene: "work",
            register: "敬語",
          },
          {
            japanese: "子供にスマホを使わせすぎないようにしている。",
            tokens: [
              { text: "子供", kana: "こども" },
              { text: "にスマホを" },
              { text: "使", kana: "つか" },
              { text: "わせすぎないようにしている。" },
            ],
            kana: "こどもにすまほをつかわせすぎないようにしている。",
            chinese: "尽量控制孩子使用手机的时间。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
      {
        conjugationType: "causativePassive",
        conjugatedForm: "使わされる",
        explanationZh: "被迫使用；被强制要求用某样东西（五段缩约形）",
        patternHint: "五段縮約：使わ + される（使わせられる の口語形）",
        examples: [
          {
            japanese: "古いシステムをずっと使わされていた。",
            tokens: [
              { text: "古", kana: "ふる" },
              { text: "いシステムをずっと" },
              { text: "使", kana: "つか" },
              { text: "わされていた。" },
            ],
            kana: "ふるいしすてむをずっとつかわされていた。",
            chinese: "被迫一直使用老旧的系统。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "使いにくい道具を使わされた。",
            tokens: [
              { text: "使", kana: "つか" },
              { text: "いにくい" },
              { text: "道具", kana: "どうぐ" },
              { text: "を" },
              { text: "使", kana: "つか" },
              { text: "わされた。" },
            ],
            kana: "つかいにくいどうぐをつかわされた。",
            chinese: "被强迫用了很难使的工具。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
    ],
  },

  // ======== 送る ========
  {
    id: "okuru",
    dictionaryForm: "送る",
    verbGroup: "godan",
    meaningZh: "发送；送",
    conjugations: [
      {
        conjugationType: "passive",
        conjugatedForm: "送られる",
        explanationZh: "被发来；被送去",
        patternHint: "五段：語幹 + あ段 + れる（送る → 送ら + れる）",
        examples: [
          {
            japanese: "大量のメールが一気に送られてきた。",
            tokens: [
              { text: "大量", kana: "たいりょう" },
              { text: "のメールが" },
              { text: "一気", kana: "いっき" },
              { text: "に" },
              { text: "送", kana: "おく" },
              { text: "られてきた。" },
            ],
            kana: "たいりょうのめーるがいっきにおくられてきた。",
            chinese: "一下子涌来了大量邮件。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "誕生日に友達から花束を送られた。",
            tokens: [
              { text: "誕生日", kana: "たんじょうび" },
              { text: "に" },
              { text: "友達", kana: "ともだち" },
              { text: "から" },
              { text: "花束", kana: "はなたば" },
              { text: "を" },
              { text: "送", kana: "おく" },
              { text: "られた。" },
            ],
            kana: "たんじょうびにともだちからはなたばをおくられた。",
            chinese: "生日当天收到了朋友送来的一束花。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
      {
        conjugationType: "causative",
        conjugatedForm: "送らせる",
        explanationZh: "让…发送；命令或请求发送",
        patternHint: "五段：語幹 + あ段 + せる（送る → 送ら + せる）",
        examples: [
          {
            japanese: "部下に書類を送らせてください。",
            tokens: [
              { text: "部下", kana: "ぶか" },
              { text: "に" },
              { text: "書類", kana: "しょるい" },
              { text: "を" },
              { text: "送", kana: "おく" },
              { text: "らせてください。" },
            ],
            kana: "ぶかにしょるいをおくらせてください。",
            chinese: "请让下属发送一下文件。",
            scene: "work",
            register: "丁寧",
          },
          {
            japanese: "子供を塾まで車で送らせてもらった。",
            tokens: [
              { text: "子供", kana: "こども" },
              { text: "を" },
              { text: "塾", kana: "じゅく" },
              { text: "まで" },
              { text: "車", kana: "くるま" },
              { text: "で" },
              { text: "送", kana: "おく" },
              { text: "らせてもらった。" },
            ],
            kana: "こどもをじゅくまでくるまでおくらせてもらった。",
            chinese: "承蒙开车把孩子送到了补习班。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
      {
        conjugationType: "causativePassive",
        conjugatedForm: "送らされる",
        explanationZh: "被迫发送；被强制要求去送（五段缩约形）",
        patternHint: "五段縮約：送ら + される（送らせられる の口語形）",
        examples: [
          {
            japanese: "深夜にも大量の資料を送らされた。",
            tokens: [
              { text: "深夜", kana: "しんや" },
              { text: "にも" },
              { text: "大量", kana: "たいりょう" },
              { text: "の" },
              { text: "資料", kana: "しりょう" },
              { text: "を" },
              { text: "送", kana: "おく" },
              { text: "らされた。" },
            ],
            kana: "しんやにもたいりょうのしりょうをおくらされた。",
            chinese: "深夜也被要求发送了大量资料。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "遠い場所まで荷物を送らされた。",
            tokens: [
              { text: "遠", kana: "とお" },
              { text: "い" },
              { text: "場所", kana: "ばしょ" },
              { text: "まで" },
              { text: "荷物", kana: "にもつ" },
              { text: "を" },
              { text: "送", kana: "おく" },
              { text: "らされた。" },
            ],
            kana: "とおいばしょまでにもつをおくらされた。",
            chinese: "被强制要求把行李发送到了很远的地方。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
    ],
  },

  // ======== 見る ========
  {
    id: "miru",
    dictionaryForm: "見る",
    verbGroup: "ichidan",
    meaningZh: "看；查看",
    conjugations: [
      {
        conjugationType: "passive",
        conjugatedForm: "見られる",
        explanationZh: "被看；被注视（一段动词被动与可能同形）",
        patternHint: "一段：語幹 + られる（見る → 見 + られる）",
        examples: [
          {
            japanese: "プレゼン中に資料の誤字を見られてしまった。",
            tokens: [
              { text: "プレゼン" },
              { text: "中", kana: "ちゅう" },
              { text: "に" },
              { text: "資料", kana: "しりょう" },
              { text: "の" },
              { text: "誤字", kana: "ごじ" },
              { text: "を" },
              { text: "見", kana: "み" },
              { text: "られてしまった。" },
            ],
            kana: "ぷれぜんちゅうにしりょうのごじをみられてしまった。",
            chinese: "演示中资料上的错字被人发现了。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "転んだところを人に見られて恥ずかしかった。",
            tokens: [
              { text: "転", kana: "ころ" },
              { text: "んだところを" },
              { text: "人", kana: "ひと" },
              { text: "に" },
              { text: "見", kana: "み" },
              { text: "られて" },
              { text: "恥", kana: "は" },
              { text: "ずかしかった。" },
            ],
            kana: "ころんだところをひとにみられてはずかしかった。",
            chinese: "摔跤的样子被人看到了，好尴尬。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
      {
        conjugationType: "causative",
        conjugatedForm: "見させる",
        explanationZh: "让…看；要求或允许某人查看",
        patternHint: "一段：語幹 + させる（見る → 見 + させる）",
        examples: [
          {
            japanese: "上司にデータを見させてください。",
            tokens: [
              { text: "上司", kana: "じょうし" },
              { text: "にデータを" },
              { text: "見", kana: "み" },
              { text: "させてください。" },
            ],
            kana: "じょうしにでーたをみさせてください。",
            chinese: "请让上司看一下数据。",
            scene: "work",
            register: "丁寧",
          },
          {
            japanese: "子供に毎日ニュースを見させる。",
            tokens: [
              { text: "子供", kana: "こども" },
              { text: "に" },
              { text: "毎日", kana: "まいにち" },
              { text: "ニュースを" },
              { text: "見", kana: "み" },
              { text: "させる。" },
            ],
            kana: "こどもにまいにちにゅーすをみさせる。",
            chinese: "每天让孩子看新闻。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
      {
        conjugationType: "causativePassive",
        conjugatedForm: "見させられる",
        explanationZh: "被迫观看；被强制要求去看",
        patternHint: "一段：見 + させられる",
        examples: [
          {
            japanese: "長い会議の録画を全員見させられた。",
            tokens: [
              { text: "長", kana: "なが" },
              { text: "い" },
              { text: "会議", kana: "かいぎ" },
              { text: "の" },
              { text: "録画", kana: "ろくが" },
              { text: "を" },
              { text: "全員", kana: "ぜんいん" },
              { text: "見", kana: "み" },
              { text: "させられた。" },
            ],
            kana: "ながいかいぎのろくがをぜんいんみさせられた。",
            chinese: "所有人都被强迫看了很长的会议录像。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "怖い映画を見させられてトラウマになった。",
            tokens: [
              { text: "怖", kana: "こわ" },
              { text: "い" },
              { text: "映画", kana: "えいが" },
              { text: "を" },
              { text: "見", kana: "み" },
              { text: "させられてトラウマになった。" },
            ],
            kana: "こわいえいがをみさせられてとらうまになった。",
            chinese: "被强迫看了恐怖电影，留下了心理阴影。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
    ],
  },

  // ======== 食べる ========
  {
    id: "taberu",
    dictionaryForm: "食べる",
    verbGroup: "ichidan",
    meaningZh: "吃",
    conjugations: [
      {
        conjugationType: "passive",
        conjugatedForm: "食べられる",
        explanationZh: "被吃；东西被别人吃了（也可表可能）",
        patternHint: "一段：語幹 + られる（食べる → 食べ + られる）",
        examples: [
          {
            japanese: "差し入れのお菓子がすぐに食べられた。",
            tokens: [
              { text: "差し入れ", kana: "さしいれ" },
              { text: "の" },
              { text: "お" },
              { text: "菓子", kana: "かし" },
              { text: "がすぐに" },
              { text: "食", kana: "た" },
              { text: "べられた。" },
            ],
            kana: "さしいれのおかしがすぐにたべられた。",
            chinese: "带去的点心很快就被大家吃光了。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "大事なケーキを犬に食べられてしまった。",
            tokens: [
              { text: "大事", kana: "たいじ" },
              { text: "なケーキを" },
              { text: "犬", kana: "いぬ" },
              { text: "に" },
              { text: "食", kana: "た" },
              { text: "べられてしまった。" },
            ],
            kana: "たいじなけーきをいぬにたべられてしまった。",
            chinese: "珍藏的蛋糕被狗吃掉了。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
      {
        conjugationType: "causative",
        conjugatedForm: "食べさせる",
        explanationZh: "让…吃；喂给某人吃",
        patternHint: "一段：語幹 + させる（食べる → 食べ + させる）",
        examples: [
          {
            japanese: "スタッフに昼食を食べさせてから戻ります。",
            tokens: [
              { text: "スタッフに" },
              { text: "昼食", kana: "ちゅうしょく" },
              { text: "を" },
              { text: "食", kana: "た" },
              { text: "べさせてから" },
              { text: "戻", kana: "もど" },
              { text: "ります。" },
            ],
            kana: "すたっふにちゅうしょくをたべさせてからもどります。",
            chinese: "让员工吃完午饭再回去。",
            scene: "work",
            register: "丁寧",
          },
          {
            japanese: "子供に好き嫌いなく野菜を食べさせたい。",
            tokens: [
              { text: "子供", kana: "こども" },
              { text: "に" },
              { text: "好", kana: "す" },
              { text: "き" },
              { text: "嫌", kana: "きら" },
              { text: "いなく" },
              { text: "野菜", kana: "やさい" },
              { text: "を" },
              { text: "食", kana: "た" },
              { text: "べさせたい。" },
            ],
            kana: "こどもにすききらいなくやさいをたべさせたい。",
            chinese: "希望让孩子不挑食地把蔬菜吃掉。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
      {
        conjugationType: "causativePassive",
        conjugatedForm: "食べさせられる",
        explanationZh: "被迫吃；被强制要求去吃",
        patternHint: "一段：食べ + させられる",
        examples: [
          {
            japanese: "接待で苦手な料理を食べさせられた。",
            tokens: [
              { text: "接待", kana: "せったい" },
              { text: "で" },
              { text: "苦手", kana: "にがて" },
              { text: "な" },
              { text: "料理", kana: "りょうり" },
              { text: "を" },
              { text: "食", kana: "た" },
              { text: "べさせられた。" },
            ],
            kana: "せったいでにがてなりょうりをたべさせられた。",
            chinese: "在接待宴上被强迫吃了不擅长的料理。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "子供のころ、嫌いなものを食べさせられた。",
            tokens: [
              { text: "子供", kana: "こども" },
              { text: "のころ、" },
              { text: "嫌", kana: "きら" },
              { text: "いなものを" },
              { text: "食", kana: "た" },
              { text: "べさせられた。" },
            ],
            kana: "こどものころ、きらいなものをたべさせられた。",
            chinese: "小时候被强迫吃了讨厌的东西。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
    ],
  },

  // ======== 起きる ========
  {
    id: "okiru",
    dictionaryForm: "起きる",
    verbGroup: "ichidan",
    meaningZh: "起床；发生",
    conjugations: [
      {
        conjugationType: "passive",
        conjugatedForm: "起きられる",
        explanationZh: "（迷惑受身）被他人起床所累；受到波及",
        patternHint: "一段：語幹 + られる（起きる → 起き + られる）",
        examples: [
          {
            japanese: "夜中に子供に起きられて全然眠れなかった。",
            tokens: [
              { text: "夜中", kana: "よなか" },
              { text: "に" },
              { text: "子供", kana: "こども" },
              { text: "に" },
              { text: "起", kana: "お" },
              { text: "きられて" },
              { text: "全然", kana: "ぜんぜん" },
              { text: "眠", kana: "ねむ" },
              { text: "れなかった。" },
            ],
            kana: "よなかにこどもにおきられてぜんぜんねむれなかった。",
            chinese: "半夜孩子起来了，害得自己完全睡不着。",
            scene: "life",
            register: "カジュアル",
          },
          {
            japanese: "深夜に同僚に起きられて電話対応を頼まれた。",
            tokens: [
              { text: "深夜", kana: "しんや" },
              { text: "に" },
              { text: "同僚", kana: "どうりょう" },
              { text: "に" },
              { text: "起", kana: "お" },
              { text: "きられて" },
              { text: "電話", kana: "でんわ" },
              { text: "対応", kana: "たいおう" },
              { text: "を" },
              { text: "頼", kana: "たの" },
              { text: "まれた。" },
            ],
            kana: "しんやにどうりょうにおきられてでんわたいおうをたのまれた。",
            chinese: "深夜被同事叫醒，不得不处理电话。",
            scene: "work",
            register: "カジュアル",
          },
        ],
      },
      {
        conjugationType: "causative",
        conjugatedForm: "起きさせる",
        explanationZh: "让…起床；使某人起来",
        patternHint: "一段：語幹 + させる（起きる → 起き + させる）",
        examples: [
          {
            japanese: "早朝の会議のためにスタッフを六時に起きさせた。",
            tokens: [
              { text: "早朝", kana: "そうちょう" },
              { text: "の" },
              { text: "会議", kana: "かいぎ" },
              { text: "のためにスタッフを" },
              { text: "六時", kana: "ろくじ" },
              { text: "に" },
              { text: "起", kana: "お" },
              { text: "きさせた。" },
            ],
            kana: "そうちょうのかいぎのためにすたっふをろくじにおきさせた。",
            chinese: "为了早上的会议，让员工六点就起来了。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "子供を毎朝六時に起きさせる。",
            tokens: [
              { text: "子供", kana: "こども" },
              { text: "を" },
              { text: "毎朝", kana: "まいあさ" },
              { text: "六時", kana: "ろくじ" },
              { text: "に" },
              { text: "起", kana: "お" },
              { text: "きさせる。" },
            ],
            kana: "こどもをまいあさろくじにおきさせる。",
            chinese: "每天早上六点让孩子起床。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
      {
        conjugationType: "causativePassive",
        conjugatedForm: "起きさせられる",
        explanationZh: "被迫起床；被强制要求早起",
        patternHint: "一段：起き + させられる",
        examples: [
          {
            japanese: "早朝研修のために五時に起きさせられた。",
            tokens: [
              { text: "早朝", kana: "そうちょう" },
              { text: "研修", kana: "けんしゅう" },
              { text: "のために" },
              { text: "五時", kana: "ごじ" },
              { text: "に" },
              { text: "起", kana: "お" },
              { text: "きさせられた。" },
            ],
            kana: "そうちょうけんしゅうのためにごじにおきさせられた。",
            chinese: "为了早晨的培训，被强迫五点就起床了。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "毎朝早く起きさせられて疲れる。",
            tokens: [
              { text: "毎朝", kana: "まいあさ" },
              { text: "早", kana: "はや" },
              { text: "く" },
              { text: "起", kana: "お" },
              { text: "きさせられて" },
              { text: "疲", kana: "つか" },
              { text: "れる。" },
            ],
            kana: "まいあさはやくおきさせられてつかれる。",
            chinese: "每天早上都被强迫早起，累得不行。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
    ],
  },

  // ======== する ========
  {
    id: "suru",
    dictionaryForm: "する",
    verbGroup: "irregular",
    meaningZh: "做",
    conjugations: [
      {
        conjugationType: "passive",
        conjugatedForm: "される",
        explanationZh: "被做；受到某动作（也可表示尊敬）",
        patternHint: "不規則：する → される",
        examples: [
          {
            japanese: "会議でミスを指摘されてしまいました。",
            tokens: [
              { text: "会議", kana: "かいぎ" },
              { text: "でミスを" },
              { text: "指摘", kana: "してき" },
              { text: "されてしまいました。" },
            ],
            kana: "かいぎでみすをしてきされてしまいました。",
            chinese: "在会议上被指出了失误。",
            scene: "work",
            register: "丁寧",
          },
          {
            japanese: "友達にドタキャンされて予定が台無しになった。",
            tokens: [
              { text: "友達", kana: "ともだち" },
              { text: "にドタキャンされて" },
              { text: "予定", kana: "よてい" },
              { text: "が" },
              { text: "台無し", kana: "だいなし" },
              { text: "になった。" },
            ],
            kana: "ともだちにどたきゃんされてよていがだいなしになった。",
            chinese: "被朋友临时放鸽子，计划全泡汤了。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
      {
        conjugationType: "causative",
        conjugatedForm: "させる",
        explanationZh: "让…做；命令或允许某人做某事",
        patternHint: "不規則：する → させる",
        examples: [
          {
            japanese: "新人に資料の整理をさせた。",
            tokens: [
              { text: "新人", kana: "しんじん" },
              { text: "に" },
              { text: "資料", kana: "しりょう" },
              { text: "の" },
              { text: "整理", kana: "せいり" },
              { text: "をさせた。" },
            ],
            kana: "しんじんにしりょうのせいりをさせた。",
            chinese: "让新员工整理了资料。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "宿題を終わらせてから外で遊ばせる。",
            tokens: [
              { text: "宿題", kana: "しゅくだい" },
              { text: "を" },
              { text: "終", kana: "お" },
              { text: "わらせてから" },
              { text: "外", kana: "そと" },
              { text: "で" },
              { text: "遊", kana: "あそ" },
              { text: "ばせる。" },
            ],
            kana: "しゅくだいをおわらせてからそとであそばせる。",
            chinese: "做完作业之后才让去外面玩。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
      {
        conjugationType: "causativePassive",
        conjugatedForm: "させられる",
        explanationZh: "被迫做；被强制要求去做某事",
        patternHint: "不規則：する → させられる",
        examples: [
          {
            japanese: "不本意なプロジェクトを担当させられた。",
            tokens: [
              { text: "不本意", kana: "ふほんい" },
              { text: "なプロジェクトを" },
              { text: "担当", kana: "たんとう" },
              { text: "させられた。" },
            ],
            kana: "ふほんいなぷろじぇくとをたんとうさせられた。",
            chinese: "被安排负责了并不情愿的项目。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "子供のころ、ピアノを練習させられた。",
            tokens: [
              { text: "子供", kana: "こども" },
              { text: "のころ、ピアノを" },
              { text: "練習", kana: "れんしゅう" },
              { text: "させられた。" },
            ],
            kana: "こどものころ、ぴあのをれんしゅうさせられた。",
            chinese: "小时候被强迫练了钢琴。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
    ],
  },

  // ======== 来る ========
  {
    id: "kuru",
    dictionaryForm: "来る",
    verbGroup: "irregular",
    meaningZh: "来",
    conjugations: [
      {
        conjugationType: "passive",
        conjugatedForm: "来られる",
        explanationZh: "（迷惑受身）对方来访反而造成困扰",
        patternHint: "不規則：来る → 来られる（こられる）",
        examples: [
          {
            japanese: "お客様に急に来られて対応が大変でした。",
            tokens: [
              { text: "お" },
              { text: "客様", kana: "きゃくさま" },
              { text: "に" },
              { text: "急", kana: "きゅう" },
              { text: "に" },
              { text: "来", kana: "こ" },
              { text: "られて" },
              { text: "対応", kana: "たいおう" },
              { text: "が" },
              { text: "大変", kana: "たいへん" },
              { text: "でした。" },
            ],
            kana: "おきゃくさまにきゅうにこられてたいおうがたいへんでした。",
            chinese: "客户突然来访，应对起来非常吃力。",
            scene: "work",
            register: "丁寧",
          },
          {
            japanese: "夜遅くに友達に来られて困った。",
            tokens: [
              { text: "夜遅く", kana: "よるおそく" },
              { text: "に" },
              { text: "友達", kana: "ともだち" },
              { text: "に" },
              { text: "来", kana: "こ" },
              { text: "られて" },
              { text: "困", kana: "こま" },
              { text: "った。" },
            ],
            kana: "よるおそくにともだちにこられてこまった。",
            chinese: "朋友深夜突然来访，让我很为难。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
      {
        conjugationType: "causative",
        conjugatedForm: "来させる",
        explanationZh: "让…来；要求或使某人前来",
        patternHint: "不規則：来る → 来させる（こさせる）",
        examples: [
          {
            japanese: "取引先を東京まで来させるのは申し訳ない。",
            tokens: [
              { text: "取引先", kana: "とりひきさき" },
              { text: "を" },
              { text: "東京", kana: "とうきょう" },
              { text: "まで" },
              { text: "来", kana: "こ" },
              { text: "させるのは" },
              { text: "申し訳", kana: "もうしわけ" },
              { text: "ない。" },
            ],
            kana: "とりひきさきをとうきょうまでこさせるのはもうしわけない。",
            chinese: "让合作方特意来东京，实在过意不去。",
            scene: "work",
            register: "丁寧",
          },
          {
            japanese: "遠くから親を来させてしまって申し訳なかった。",
            tokens: [
              { text: "遠く", kana: "とおく" },
              { text: "から" },
              { text: "親", kana: "おや" },
              { text: "を" },
              { text: "来", kana: "こ" },
              { text: "させてしまって" },
              { text: "申し訳", kana: "もうしわけ" },
              { text: "なかった。" },
            ],
            kana: "とおくからおやをこさせてしまってもうしわけなかった。",
            chinese: "让父母从远处赶来，真是太抱歉了。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
      {
        conjugationType: "causativePassive",
        conjugatedForm: "来させられる",
        explanationZh: "被迫来；被强制要求前来",
        patternHint: "不規則：来る → 来させられる（こさせられる）",
        examples: [
          {
            japanese: "休日にも会社に来させられた。",
            tokens: [
              { text: "休日", kana: "きゅうじつ" },
              { text: "にも" },
              { text: "会社", kana: "かいしゃ" },
              { text: "に" },
              { text: "来", kana: "こ" },
              { text: "させられた。" },
            ],
            kana: "きゅうじつにもかいしゃにこさせられた。",
            chinese: "休息日也被叫到公司去了。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "親の用事で遠くまで来させられた。",
            tokens: [
              { text: "親", kana: "おや" },
              { text: "の" },
              { text: "用事", kana: "ようじ" },
              { text: "で" },
              { text: "遠く", kana: "とおく" },
              { text: "まで" },
              { text: "来", kana: "こ" },
              { text: "させられた。" },
            ],
            kana: "おやのようじでとおくまでこさせられた。",
            chinese: "因父母的事情，被迫去了很远的地方。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
    ],
  },

  // ======== 持つ ========
  {
    id: "motsu",
    dictionaryForm: "持つ",
    verbGroup: "godan",
    meaningZh: "拿；持有",
    conjugations: [
      {
        conjugationType: "passive",
        conjugatedForm: "持たれる",
        explanationZh: "被拿；被持有（也表示被人怀有某种想法）",
        patternHint: "五段：語幹 + あ段 + れる（持つ → 持た + れる）",
        examples: [
          {
            japanese: "プロジェクトへの疑問を部下に持たれてしまった。",
            tokens: [
              { text: "プロジェクトへの" },
              { text: "疑問", kana: "ぎもん" },
              { text: "を" },
              { text: "部下", kana: "ぶか" },
              { text: "に" },
              { text: "持", kana: "も" },
              { text: "たれてしまった。" },
            ],
            kana: "ぷろじぇくとへのぎもんをぶかにもたれてしまった。",
            chinese: "让下属对项目产生了疑问。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "荷物を人に持たれて、逆に困ってしまった。",
            tokens: [
              { text: "荷物", kana: "にもつ" },
              { text: "を" },
              { text: "人", kana: "ひと" },
              { text: "に" },
              { text: "持", kana: "も" },
              { text: "たれて、" },
              { text: "逆", kana: "ぎゃく" },
              { text: "に" },
              { text: "困", kana: "こま" },
              { text: "ってしまった。" },
            ],
            kana: "にもつをひとにもたれて、ぎゃくにこまってしまった。",
            chinese: "被别人帮忙拿了行李，反而感到不知所措。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
      {
        conjugationType: "causative",
        conjugatedForm: "持たせる",
        explanationZh: "让…拿；叫某人携带或持有",
        patternHint: "五段：語幹 + あ段 + せる（持つ → 持た + せる）",
        examples: [
          {
            japanese: "新人にファイルを持たせた。",
            tokens: [
              { text: "新人", kana: "しんじん" },
              { text: "にファイルを" },
              { text: "持", kana: "も" },
              { text: "たせた。" },
            ],
            kana: "しんじんにふぁいるをもたせた。",
            chinese: "让新员工拿了文件。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "子供に自分のリュックを持たせる。",
            tokens: [
              { text: "子供", kana: "こども" },
              { text: "に" },
              { text: "自分", kana: "じぶん" },
              { text: "のリュックを" },
              { text: "持", kana: "も" },
              { text: "たせる。" },
            ],
            kana: "こどもにじぶんのりゅっくをもたせる。",
            chinese: "让孩子自己背书包。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
      {
        conjugationType: "causativePassive",
        conjugatedForm: "持たされる",
        explanationZh: "被迫拿；被强制要求携带（五段缩约形）",
        patternHint: "五段縮約：持た + される（持たせられる の口語形）",
        examples: [
          {
            japanese: "大量の荷物を持たされて肩が痛い。",
            tokens: [
              { text: "大量", kana: "たいりょう" },
              { text: "の" },
              { text: "荷物", kana: "にもつ" },
              { text: "を" },
              { text: "持", kana: "も" },
              { text: "たされて" },
              { text: "肩", kana: "かた" },
              { text: "が" },
              { text: "痛", kana: "いた" },
              { text: "い。" },
            ],
            kana: "たいりょうのにもつをもたされてかたがいたい。",
            chinese: "被要求拿了大量行李，肩膀都痛了。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "友達の荷物まで持たされた。",
            tokens: [
              { text: "友達", kana: "ともだち" },
              { text: "の" },
              { text: "荷物", kana: "にもつ" },
              { text: "まで" },
              { text: "持", kana: "も" },
              { text: "たされた。" },
            ],
            kana: "ともだちのにもつまでもたされた。",
            chinese: "连朋友的行李也被要求帮忙拿了。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
    ],
  },

  // ======== 飲む ========
  {
    id: "nomu",
    dictionaryForm: "飲む",
    verbGroup: "godan",
    meaningZh: "喝",
    conjugations: [
      {
        conjugationType: "passive",
        conjugatedForm: "飲まれる",
        explanationZh: "被喝；东西被别人喝了",
        patternHint: "五段：語幹 + あ段 + れる（飲む → 飲ま + れる）",
        examples: [
          {
            japanese: "接待用に用意したワインを全部飲まれてしまった。",
            tokens: [
              { text: "接待", kana: "せったい" },
              { text: "用", kana: "よう" },
              { text: "に" },
              { text: "用意", kana: "ようい" },
              { text: "したワインを" },
              { text: "全部", kana: "ぜんぶ" },
              { text: "飲", kana: "の" },
              { text: "まれてしまった。" },
            ],
            kana: "せったいようにようい したわいんをぜんぶのまれてしまった。",
            chinese: "为接待准备的葡萄酒被全部喝光了。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "冷蔵庫のビールを友達に全部飲まれた。",
            tokens: [
              { text: "冷蔵庫", kana: "れいぞうこ" },
              { text: "のビールを" },
              { text: "友達", kana: "ともだち" },
              { text: "に" },
              { text: "全部", kana: "ぜんぶ" },
              { text: "飲", kana: "の" },
              { text: "まれた。" },
            ],
            kana: "れいぞうこのびーるをともだちにぜんぶのまれた。",
            chinese: "冰箱里的啤酒被朋友全喝掉了。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
      {
        conjugationType: "causative",
        conjugatedForm: "飲ませる",
        explanationZh: "让…喝；让某人饮用",
        patternHint: "五段：語幹 + あ段 + せる（飲む → 飲ま + せる）",
        examples: [
          {
            japanese: "お客様にお茶を飲ませてください。",
            tokens: [
              { text: "お" },
              { text: "客様", kana: "きゃくさま" },
              { text: "にお" },
              { text: "茶", kana: "ちゃ" },
              { text: "を" },
              { text: "飲", kana: "の" },
              { text: "ませてください。" },
            ],
            kana: "おきゃくさまにおちゃをのませてください。",
            chinese: "请让客人喝杯茶。",
            scene: "work",
            register: "丁寧",
          },
          {
            japanese: "薬を嫌がる子供に飲ませるのが大変だ。",
            tokens: [
              { text: "薬", kana: "くすり" },
              { text: "を" },
              { text: "嫌", kana: "いや" },
              { text: "がる" },
              { text: "子供", kana: "こども" },
              { text: "に" },
              { text: "飲", kana: "の" },
              { text: "ませるのが" },
              { text: "大変", kana: "たいへん" },
              { text: "だ。" },
            ],
            kana: "くすりをいやがるこどもにのませるのがたいへんだ。",
            chinese: "让不肯吃药的孩子把药喝下去真是不容易。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
      {
        conjugationType: "causativePassive",
        conjugatedForm: "飲まされる",
        explanationZh: "被迫喝；被强制要求饮用（五段缩约形）",
        patternHint: "五段縮約：飲ま + される（飲ませられる の口語形）",
        examples: [
          {
            japanese: "接待で苦手なお酒を何杯も飲まされた。",
            tokens: [
              { text: "接待", kana: "せったい" },
              { text: "で" },
              { text: "苦手", kana: "にがて" },
              { text: "なお" },
              { text: "酒", kana: "さけ" },
              { text: "を" },
              { text: "何杯", kana: "なんばい" },
              { text: "も" },
              { text: "飲", kana: "の" },
              { text: "まされた。" },
            ],
            kana: "せったいでにがてなおさけをなんばいものまされた。",
            chinese: "在接待宴上被强灌了好几杯不喜欢的酒。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "飲み会でずっとビールを飲まされた。",
            tokens: [
              { text: "飲み会", kana: "のみかい" },
              { text: "でずっとビールを" },
              { text: "飲", kana: "の" },
              { text: "まされた。" },
            ],
            kana: "のみかいでずっとびーるをのまされた。",
            chinese: "在聚餐上被一直灌啤酒。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
    ],
  },

  // ======== 聞く ========
  {
    id: "kiku",
    dictionaryForm: "聞く",
    verbGroup: "godan",
    meaningZh: "听；问",
    conjugations: [
      {
        conjugationType: "passive",
        conjugatedForm: "聞かれる",
        explanationZh: "被问到；被听到",
        patternHint: "五段：語幹 + あ段 + れる（聞く → 聞か + れる）",
        examples: [
          {
            japanese: "面接で想定外の質問を聞かれた。",
            tokens: [
              { text: "面接", kana: "めんせつ" },
              { text: "で" },
              { text: "想定外", kana: "そうていがい" },
              { text: "の" },
              { text: "質問", kana: "しつもん" },
              { text: "を" },
              { text: "聞", kana: "き" },
              { text: "かれた。" },
            ],
            kana: "めんせつでそうていがいのしつもんをきかれた。",
            chinese: "面试中被问到了意料之外的问题。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "彼女に給料のことを聞かれて困った。",
            tokens: [
              { text: "彼女", kana: "かのじょ" },
              { text: "に" },
              { text: "給料", kana: "きゅうりょう" },
              { text: "のことを" },
              { text: "聞", kana: "き" },
              { text: "かれて" },
              { text: "困", kana: "こま" },
              { text: "った。" },
            ],
            kana: "かのじょにきゅうりょうのことをきかれてこまった。",
            chinese: "被女友问到了工资的事，不知怎么回答。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
      {
        conjugationType: "causative",
        conjugatedForm: "聞かせる",
        explanationZh: "让…听；让某人倾听",
        patternHint: "五段：語幹 + あ段 + せる（聞く → 聞か + せる）",
        examples: [
          {
            japanese: "新商品の企画を全員に聞かせた。",
            tokens: [
              { text: "新商品", kana: "しんしょうひん" },
              { text: "の" },
              { text: "企画", kana: "きかく" },
              { text: "を" },
              { text: "全員", kana: "ぜんいん" },
              { text: "に" },
              { text: "聞", kana: "き" },
              { text: "かせた。" },
            ],
            kana: "しんしょうひんのきかくをぜんいんにきかせた。",
            chinese: "让所有人听了新产品的企划方案。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "子供に毎晩クラシック音楽を聞かせる。",
            tokens: [
              { text: "子供", kana: "こども" },
              { text: "に" },
              { text: "毎晩", kana: "まいばん" },
              { text: "クラシック" },
              { text: "音楽", kana: "おんがく" },
              { text: "を" },
              { text: "聞", kana: "き" },
              { text: "かせる。" },
            ],
            kana: "こどもにまいばんくらしっくおんがくをきかせる。",
            chinese: "每晚让孩子听古典音乐。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
      {
        conjugationType: "causativePassive",
        conjugatedForm: "聞かされる",
        explanationZh: "被迫听；被强制要求去听（五段缩约形）",
        patternHint: "五段縮約：聞か + される（聞かせられる の口語形）",
        examples: [
          {
            japanese: "長い会議で延々と説明を聞かされた。",
            tokens: [
              { text: "長", kana: "なが" },
              { text: "い" },
              { text: "会議", kana: "かいぎ" },
              { text: "で" },
              { text: "延々", kana: "えんえん" },
              { text: "と" },
              { text: "説明", kana: "せつめい" },
              { text: "を" },
              { text: "聞", kana: "き" },
              { text: "かされた。" },
            ],
            kana: "ながいかいぎでえんえんとせつめいをきかされた。",
            chinese: "在漫长的会议上被迫听了没完没了的说明。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "友達の愚痴を何時間も聞かされた。",
            tokens: [
              { text: "友達", kana: "ともだち" },
              { text: "の" },
              { text: "愚痴", kana: "ぐち" },
              { text: "を" },
              { text: "何時間", kana: "なんじかん" },
              { text: "も" },
              { text: "聞", kana: "き" },
              { text: "かされた。" },
            ],
            kana: "ともだちのぐちをなんじかんもきかされた。",
            chinese: "被朋友的牢骚话缠了好几个小时。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
    ],
  },

  // ======== 決める ========
  {
    id: "kimeru",
    dictionaryForm: "決める",
    verbGroup: "ichidan",
    meaningZh: "决定",
    conjugations: [
      {
        conjugationType: "passive",
        conjugatedForm: "決められる",
        explanationZh: "被决定；事情被他人单方面定下来",
        patternHint: "一段：語幹 + られる（決める → 決め + られる）",
        examples: [
          {
            japanese: "納期を一方的に決められて困っています。",
            tokens: [
              { text: "納期", kana: "のうき" },
              { text: "を" },
              { text: "一方的", kana: "いっぽうてき" },
              { text: "に" },
              { text: "決", kana: "き" },
              { text: "められて" },
              { text: "困", kana: "こま" },
              { text: "っています。" },
            ],
            kana: "のうきをいっぽうてきにきめられてこまっています。",
            chinese: "交货期被单方面定下来了，让人很为难。",
            scene: "work",
            register: "丁寧",
          },
          {
            japanese: "旅行の行き先を彼女に勝手に決められた。",
            tokens: [
              { text: "旅行", kana: "りょこう" },
              { text: "の" },
              { text: "行き先", kana: "ゆきさき" },
              { text: "を" },
              { text: "彼女", kana: "かのじょ" },
              { text: "に" },
              { text: "勝手", kana: "かって" },
              { text: "に" },
              { text: "決", kana: "き" },
              { text: "められた。" },
            ],
            kana: "りょこうのゆきさきをかのじょにかってにきめられた。",
            chinese: "旅行目的地被女友自作主张定好了。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
      {
        conjugationType: "causative",
        conjugatedForm: "決めさせる",
        explanationZh: "让…决定；让某人做出决定",
        patternHint: "一段：語幹 + させる（決める → 決め + させる）",
        examples: [
          {
            japanese: "担当者に仕様を決めさせてください。",
            tokens: [
              { text: "担当者", kana: "たんとうしゃ" },
              { text: "に" },
              { text: "仕様", kana: "しよう" },
              { text: "を" },
              { text: "決", kana: "き" },
              { text: "めさせてください。" },
            ],
            kana: "たんとうしゃにしようをきめさせてください。",
            chinese: "请让负责人来决定规格。",
            scene: "work",
            register: "丁寧",
          },
          {
            japanese: "子供に好きな習い事を自分で決めさせた。",
            tokens: [
              { text: "子供", kana: "こども" },
              { text: "に" },
              { text: "好", kana: "す" },
              { text: "きな" },
              { text: "習い事", kana: "ならいごと" },
              { text: "を" },
              { text: "自分", kana: "じぶん" },
              { text: "で" },
              { text: "決", kana: "き" },
              { text: "めさせた。" },
            ],
            kana: "こどもにすきならならいごとをじぶんできめさせた。",
            chinese: "让孩子自己选了喜欢的兴趣班。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
      {
        conjugationType: "causativePassive",
        conjugatedForm: "決めさせられる",
        explanationZh: "被迫决定；被强制要求做出某决定",
        patternHint: "一段：決め + させられる",
        examples: [
          {
            japanese: "自分の意見を無視されて、会社の都合で決めさせられた。",
            tokens: [
              { text: "自分", kana: "じぶん" },
              { text: "の" },
              { text: "意見", kana: "いけん" },
              { text: "を" },
              { text: "無視", kana: "むし" },
              { text: "されて、" },
              { text: "会社", kana: "かいしゃ" },
              { text: "の" },
              { text: "都合", kana: "つごう" },
              { text: "で" },
              { text: "決", kana: "き" },
              { text: "めさせられた。" },
            ],
            kana: "じぶんのいけんをむしされて、かいしゃのつごうできめさせられた。",
            chinese: "自己的意见被无视，被迫按公司意愿作了决定。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "親に進路を勝手に決めさせられた。",
            tokens: [
              { text: "親", kana: "おや" },
              { text: "に" },
              { text: "進路", kana: "しんろ" },
              { text: "を" },
              { text: "勝手", kana: "かって" },
              { text: "に" },
              { text: "決", kana: "き" },
              { text: "めさせられた。" },
            ],
            kana: "おやにしんろをかってにきめさせられた。",
            chinese: "升学方向被父母强行定下来了。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
    ],
  },

  // ======== 教える ========
  {
    id: "oshieru",
    dictionaryForm: "教える",
    verbGroup: "ichidan",
    meaningZh: "教；告诉",
    conjugations: [
      {
        conjugationType: "passive",
        conjugatedForm: "教えられる",
        explanationZh: "被教；受到指导",
        patternHint: "一段：語幹 + られる（教える → 教え + られる）",
        examples: [
          {
            japanese: "上司に新しい業務フローを教えられた。",
            tokens: [
              { text: "上司", kana: "じょうし" },
              { text: "に" },
              { text: "新", kana: "あたら" },
              { text: "しい" },
              { text: "業務", kana: "ぎょうむ" },
              { text: "フローを" },
              { text: "教", kana: "おし" },
              { text: "えられた。" },
            ],
            kana: "じょうしにあたらしいぎょうむふろーをおしえられた。",
            chinese: "被上司教了新的业务流程。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "祖母に料理のコツを教えられた。",
            tokens: [
              { text: "祖母", kana: "そぼ" },
              { text: "に" },
              { text: "料理", kana: "りょうり" },
              { text: "のコツを" },
              { text: "教", kana: "おし" },
              { text: "えられた。" },
            ],
            kana: "そぼにりょうりのこつをおしえられた。",
            chinese: "被祖母教了做菜的诀窍。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
      {
        conjugationType: "causative",
        conjugatedForm: "教えさせる",
        explanationZh: "让…教；让某人去指导他人",
        patternHint: "一段：語幹 + させる（教える → 教え + させる）",
        examples: [
          {
            japanese: "ベテランに新人へのOJTを教えさせた。",
            tokens: [
              { text: "ベテランに" },
              { text: "新人", kana: "しんじん" },
              { text: "へのOJTを" },
              { text: "教", kana: "おし" },
              { text: "えさせた。" },
            ],
            kana: "べてらんにしんじんへのOJTをおしえさせた。",
            chinese: "让老员工对新员工进行了在职培训。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "娘に妹へ英語を教えさせた。",
            tokens: [
              { text: "娘", kana: "むすめ" },
              { text: "に" },
              { text: "妹", kana: "いもうと" },
              { text: "へ" },
              { text: "英語", kana: "えいご" },
              { text: "を" },
              { text: "教", kana: "おし" },
              { text: "えさせた。" },
            ],
            kana: "むすめにいもうとへえいごをおしえさせた。",
            chinese: "让女儿去教妹妹英语。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
      {
        conjugationType: "causativePassive",
        conjugatedForm: "教えさせられる",
        explanationZh: "被迫教；被强制要求去指导他人",
        patternHint: "一段：教え + させられる",
        examples: [
          {
            japanese: "苦手な分野を新人に教えさせられた。",
            tokens: [
              { text: "苦手", kana: "にがて" },
              { text: "な" },
              { text: "分野", kana: "ぶんや" },
              { text: "を" },
              { text: "新人", kana: "しんじん" },
              { text: "に" },
              { text: "教", kana: "おし" },
              { text: "えさせられた。" },
            ],
            kana: "にがてなぶんやをしんじんにおしえさせられた。",
            chinese: "被要求给新员工讲了自己并不擅长的领域。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "子供に算数を毎日教えさせられるが、難しい。",
            tokens: [
              { text: "子供", kana: "こども" },
              { text: "に" },
              { text: "算数", kana: "さんすう" },
              { text: "を" },
              { text: "毎日", kana: "まいにち" },
              { text: "教", kana: "おし" },
              { text: "えさせられるが、" },
              { text: "難", kana: "むずか" },
              { text: "しい。" },
            ],
            kana: "こどもにさんすうをまいにちおしえさせられるが、むずかしい。",
            chinese: "每天被叫来给孩子讲算数，真的很难。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
    ],
  },

  // ======== 頼む ========
  {
    id: "tanomu",
    dictionaryForm: "頼む",
    verbGroup: "godan",
    meaningZh: "拜托；请求",
    conjugations: [
      {
        conjugationType: "passive",
        conjugatedForm: "頼まれる",
        explanationZh: "被拜托；被请求去做某事",
        patternHint: "五段：語幹 + あ段 + れる（頼む → 頼ま + れる）",
        examples: [
          {
            japanese: "同僚に急な仕事を頼まれた。",
            tokens: [
              { text: "同僚", kana: "どうりょう" },
              { text: "に" },
              { text: "急", kana: "きゅう" },
              { text: "な" },
              { text: "仕事", kana: "しごと" },
              { text: "を" },
              { text: "頼", kana: "たの" },
              { text: "まれた。" },
            ],
            kana: "どうりょうにきゅうなしごとをたのまれた。",
            chinese: "被同事拜托了紧急的工作。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "友達に引っ越しを手伝うよう頼まれた。",
            tokens: [
              { text: "友達", kana: "ともだち" },
              { text: "に" },
              { text: "引っ越し", kana: "ひっこし" },
              { text: "を" },
              { text: "手伝", kana: "てつだ" },
              { text: "うよう" },
              { text: "頼", kana: "たの" },
              { text: "まれた。" },
            ],
            kana: "ともだちにひっこしをてつだうようたのまれた。",
            chinese: "被朋友拜托帮忙搬家了。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
      {
        conjugationType: "causative",
        conjugatedForm: "頼ませる",
        explanationZh: "让…去拜托；让某人提出请求",
        patternHint: "五段：語幹 + あ段 + せる（頼む → 頼ま + せる）",
        examples: [
          {
            japanese: "部下に取引先へのお願いを頼ませた。",
            tokens: [
              { text: "部下", kana: "ぶか" },
              { text: "に" },
              { text: "取引先", kana: "とりひきさき" },
              { text: "へのお" },
              { text: "願", kana: "ねが" },
              { text: "いを" },
              { text: "頼", kana: "たの" },
              { text: "ませた。" },
            ],
            kana: "ぶかにとりひきさきへのおねがいをたのませた。",
            chinese: "让下属去向合作方提出了请求。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "子供に近所のお使いを頼ませた。",
            tokens: [
              { text: "子供", kana: "こども" },
              { text: "に" },
              { text: "近所", kana: "きんじょ" },
              { text: "のお" },
              { text: "使", kana: "つか" },
              { text: "いを" },
              { text: "頼", kana: "たの" },
              { text: "ませた。" },
            ],
            kana: "こどもにきんじょのおつかいをたのませた。",
            chinese: "让孩子去附近跑了腿。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
      {
        conjugationType: "causativePassive",
        conjugatedForm: "頼まされる",
        explanationZh: "被迫接受委托；被强拉去帮忙（五段缩约形）",
        patternHint: "五段縮約：頼ま + される（頼ませられる の口語形）",
        examples: [
          {
            japanese: "自分には関係ない業務まで頼まされた。",
            tokens: [
              { text: "自分", kana: "じぶん" },
              { text: "には" },
              { text: "関係", kana: "かんけい" },
              { text: "ない" },
              { text: "業務", kana: "ぎょうむ" },
              { text: "まで" },
              { text: "頼", kana: "たの" },
              { text: "まされた。" },
            ],
            kana: "じぶんにはかんけいないぎょうむまでたのまされた。",
            chinese: "连和自己无关的事务也被拜托了。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "面倒な用事を頼まされて断れなかった。",
            tokens: [
              { text: "面倒", kana: "めんどう" },
              { text: "な" },
              { text: "用事", kana: "ようじ" },
              { text: "を" },
              { text: "頼", kana: "たの" },
              { text: "まされて" },
              { text: "断", kana: "ことわ" },
              { text: "れなかった。" },
            ],
            kana: "めんどうなようじをたのまされてことわれなかった。",
            chinese: "被拜托了麻烦的事情，没办法拒绝。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
    ],
  },

  // ======== 呼ぶ ========
  {
    id: "yobu",
    dictionaryForm: "呼ぶ",
    verbGroup: "godan",
    meaningZh: "叫；邀请",
    conjugations: [
      {
        conjugationType: "passive",
        conjugatedForm: "呼ばれる",
        explanationZh: "被叫；被召唤；被邀请",
        patternHint: "五段：語幹 + あ段 + れる（呼ぶ → 呼ば + れる）",
        examples: [
          {
            japanese: "上司に会議室に呼ばれて緊張した。",
            tokens: [
              { text: "上司", kana: "じょうし" },
              { text: "に" },
              { text: "会議室", kana: "かいぎしつ" },
              { text: "に" },
              { text: "呼", kana: "よ" },
              { text: "ばれて" },
              { text: "緊張", kana: "きんちょう" },
              { text: "した。" },
            ],
            kana: "じょうしにかいぎしつによばれてきんちょうした。",
            chinese: "被上司叫去会议室，非常紧张。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "名前を突然呼ばれてびっくりした。",
            tokens: [
              { text: "名前", kana: "なまえ" },
              { text: "を" },
              { text: "突然", kana: "とつぜん" },
              { text: "呼", kana: "よ" },
              { text: "ばれてびっくりした。" },
            ],
            kana: "なまえをとつぜんよばれてびっくりした。",
            chinese: "突然被叫到名字，吓了一跳。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
      {
        conjugationType: "causative",
        conjugatedForm: "呼ばせる",
        explanationZh: "让…叫来；让某人去叫人",
        patternHint: "五段：語幹 + あ段 + せる（呼ぶ → 呼ば + せる）",
        examples: [
          {
            japanese: "担当者を会議室に呼ばせてください。",
            tokens: [
              { text: "担当者", kana: "たんとうしゃ" },
              { text: "を" },
              { text: "会議室", kana: "かいぎしつ" },
              { text: "に" },
              { text: "呼", kana: "よ" },
              { text: "ばせてください。" },
            ],
            kana: "たんとうしゃをかいぎしつによばせてください。",
            chinese: "请让负责人来会议室。",
            scene: "work",
            register: "丁寧",
          },
          {
            japanese: "外で遊ぶ子供を家に呼ばせた。",
            tokens: [
              { text: "外", kana: "そと" },
              { text: "で" },
              { text: "遊", kana: "あそ" },
              { text: "ぶ" },
              { text: "子供", kana: "こども" },
              { text: "を" },
              { text: "家", kana: "いえ" },
              { text: "に" },
              { text: "呼", kana: "よ" },
              { text: "ばせた。" },
            ],
            kana: "そとであそぶこどもをいえによばせた。",
            chinese: "让外面玩的孩子被叫回家了。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
      {
        conjugationType: "causativePassive",
        conjugatedForm: "呼ばされる",
        explanationZh: "被迫召集；被强制叫去某地（五段缩约形）",
        patternHint: "五段縮約：呼ば + される（呼ばせられる の口語形）",
        examples: [
          {
            japanese: "休日なのに緊急で会社に呼ばされた。",
            tokens: [
              { text: "休日", kana: "きゅうじつ" },
              { text: "なのに" },
              { text: "緊急", kana: "きんきゅう" },
              { text: "で" },
              { text: "会社", kana: "かいしゃ" },
              { text: "に" },
              { text: "呼", kana: "よ" },
              { text: "ばされた。" },
            ],
            kana: "きゅうじつなのにきんきゅうでかいしゃによばされた。",
            chinese: "明明是休息日，却被紧急叫去了公司。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "気が進まないのにパーティーに呼ばされた。",
            tokens: [
              { text: "気", kana: "き" },
              { text: "が" },
              { text: "進", kana: "すす" },
              { text: "まないのにパーティーに" },
              { text: "呼", kana: "よ" },
              { text: "ばされた。" },
            ],
            kana: "きがすすまないのにぱーてぃーによばされた。",
            chinese: "虽然不情愿，还是被叫去参加了派对。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
    ],
  },

  // ======== 受ける ========
  {
    id: "ukeru",
    dictionaryForm: "受ける",
    verbGroup: "ichidan",
    meaningZh: "接受；参加",
    conjugations: [
      {
        conjugationType: "passive",
        conjugatedForm: "受けられる",
        explanationZh: "（迷惑受身）对方接下了任务反而连累自己",
        patternHint: "一段：語幹 + られる（受ける → 受け + られる）",
        examples: [
          {
            japanese: "上司に無理な依頼を受けられて、私まで残業になった。",
            tokens: [
              { text: "上司", kana: "じょうし" },
              { text: "に" },
              { text: "無理", kana: "むり" },
              { text: "な" },
              { text: "依頼", kana: "いらい" },
              { text: "を" },
              { text: "受", kana: "う" },
              { text: "けられて、私まで" },
              { text: "残業", kana: "ざんぎょう" },
              { text: "になった。" },
            ],
            kana: "じょうしにむりないらいをうけられて、わたしまでざんぎょうになった。",
            chinese: "上司接下了无理的委托，害得我也得加班。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "親に大きなローンを受けられて、家族全員が苦労した。",
            tokens: [
              { text: "親", kana: "おや" },
              { text: "に" },
              { text: "大", kana: "おお" },
              { text: "きな" },
              { text: "ローンを" },
              { text: "受", kana: "う" },
              { text: "けられて、" },
              { text: "家族", kana: "かぞく" },
              { text: "全員", kana: "ぜんいん" },
              { text: "が" },
              { text: "苦労", kana: "くろう" },
              { text: "した。" },
            ],
            kana: "おやにおおきなろーんをうけられて、かぞくぜんいんがくろうした。",
            chinese: "父亲接了大额贷款，全家人都跟着吃了苦。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
      {
        conjugationType: "causative",
        conjugatedForm: "受けさせる",
        explanationZh: "让…接受；让某人去参加或承接",
        patternHint: "一段：語幹 + させる（受ける → 受け + させる）",
        examples: [
          {
            japanese: "新人に必ず研修を受けさせる。",
            tokens: [
              { text: "新人", kana: "しんじん" },
              { text: "に" },
              { text: "必", kana: "かなら" },
              { text: "ず" },
              { text: "研修", kana: "けんしゅう" },
              { text: "を" },
              { text: "受", kana: "う" },
              { text: "けさせる。" },
            ],
            kana: "しんじんにかならずけんしゅうをうけさせる。",
            chinese: "让新员工务必参加培训。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "子供に予防接種を受けさせた。",
            tokens: [
              { text: "子供", kana: "こども" },
              { text: "に" },
              { text: "予防接種", kana: "よぼうせっしゅ" },
              { text: "を" },
              { text: "受", kana: "う" },
              { text: "けさせた。" },
            ],
            kana: "こどもによぼうせっしゅをうけさせた。",
            chinese: "让孩子打了预防针。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
      {
        conjugationType: "causativePassive",
        conjugatedForm: "受けさせられる",
        explanationZh: "被迫参加；被强制要求去接受某事",
        patternHint: "一段：受け + させられる",
        examples: [
          {
            japanese: "意味のない研修を何時間も受けさせられた。",
            tokens: [
              { text: "意味", kana: "いみ" },
              { text: "のない" },
              { text: "研修", kana: "けんしゅう" },
              { text: "を" },
              { text: "何時間", kana: "なんじかん" },
              { text: "も" },
              { text: "受", kana: "う" },
              { text: "けさせられた。" },
            ],
            kana: "いみのないけんしゅうをなんじかんもうけさせられた。",
            chinese: "被强迫参加了好几个小时毫无意义的培训。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "子供のころ、嫌いな習い事を受けさせられた。",
            tokens: [
              { text: "子供", kana: "こども" },
              { text: "のころ、" },
              { text: "嫌", kana: "きら" },
              { text: "いな" },
              { text: "習い事", kana: "ならいごと" },
              { text: "を" },
              { text: "受", kana: "う" },
              { text: "けさせられた。" },
            ],
            kana: "こどものころ、きらいならならいごとをうけさせられた。",
            chinese: "小时候被强迫参加了不喜欢的兴趣班。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
    ],
  },

  // ======== 変える ========
  {
    id: "kaeru",
    dictionaryForm: "変える",
    verbGroup: "ichidan",
    meaningZh: "改变；更改",
    conjugations: [
      {
        conjugationType: "passive",
        conjugatedForm: "変えられる",
        explanationZh: "被更改；事情被他人单方面改动",
        patternHint: "一段：語幹 + られる（変える → 変え + られる）",
        examples: [
          {
            japanese: "完成した仕様を直前に変えられて困った。",
            tokens: [
              { text: "完成", kana: "かんせい" },
              { text: "した" },
              { text: "仕様", kana: "しよう" },
              { text: "を" },
              { text: "直前", kana: "ちょくぜん" },
              { text: "に" },
              { text: "変", kana: "か" },
              { text: "えられて" },
              { text: "困", kana: "こま" },
              { text: "った。" },
            ],
            kana: "かんせいしたしようをちょくぜんにかえられてこまった。",
            chinese: "完成的规格在最后关头被改掉了，让人很为难。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "約束の場所を急に変えられた。",
            tokens: [
              { text: "約束", kana: "やくそく" },
              { text: "の" },
              { text: "場所", kana: "ばしょ" },
              { text: "を" },
              { text: "急", kana: "きゅう" },
              { text: "に" },
              { text: "変", kana: "か" },
              { text: "えられた。" },
            ],
            kana: "やくそくのばしょをきゅうにかえられた。",
            chinese: "约好的地点被突然改掉了。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
      {
        conjugationType: "causative",
        conjugatedForm: "変えさせる",
        explanationZh: "让…更改；要求某人作出改动",
        patternHint: "一段：語幹 + させる（変える → 変え + させる）",
        examples: [
          {
            japanese: "担当者にデザインを変えさせた。",
            tokens: [
              { text: "担当者", kana: "たんとうしゃ" },
              { text: "にデザインを" },
              { text: "変", kana: "か" },
              { text: "えさせた。" },
            ],
            kana: "たんとうしゃにでざいんをかえさせた。",
            chinese: "让负责人改了设计。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "子供に悪い生活習慣を変えさせた。",
            tokens: [
              { text: "子供", kana: "こども" },
              { text: "に" },
              { text: "悪", kana: "わる" },
              { text: "い" },
              { text: "生活習慣", kana: "せいかつしゅうかん" },
              { text: "を" },
              { text: "変", kana: "か" },
              { text: "えさせた。" },
            ],
            kana: "こどもにわるいせいかつしゅうかんをかえさせた。",
            chinese: "让孩子改掉了不良的生活习惯。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
      {
        conjugationType: "causativePassive",
        conjugatedForm: "変えさせられる",
        explanationZh: "被迫更改；被强制要求改动",
        patternHint: "一段：変え + させられる",
        examples: [
          {
            japanese: "完成した企画を何度も変えさせられた。",
            tokens: [
              { text: "完成", kana: "かんせい" },
              { text: "した" },
              { text: "企画", kana: "きかく" },
              { text: "を" },
              { text: "何度", kana: "なんど" },
              { text: "も" },
              { text: "変", kana: "か" },
              { text: "えさせられた。" },
            ],
            kana: "かんせいしたきかくをなんどもかえさせられた。",
            chinese: "已经完成的方案被反复要求修改。",
            scene: "work",
            register: "カジュアル",
          },
          {
            japanese: "引っ越しで生活スタイルを大きく変えさせられた。",
            tokens: [
              { text: "引っ越し", kana: "ひっこし" },
              { text: "で" },
              { text: "生活", kana: "せいかつ" },
              { text: "スタイルを" },
              { text: "大", kana: "おお" },
              { text: "きく" },
              { text: "変", kana: "か" },
              { text: "えさせられた。" },
            ],
            kana: "ひっこしでせいかつすたいるをおおきくかえさせられた。",
            chinese: "因为搬家，被迫大幅改变了生活方式。",
            scene: "life",
            register: "カジュアル",
          },
        ],
      },
    ],
  },
]
